#!/usr/bin/env python3
"""Regenerate ``mcp/data/upgrades/api_deprecations.yaml`` from an upstream source.

The Kubernetes API-deprecation data is the Upgrade Pilot's *guaranteed* core, so
it must not be hand-curated and left to rot. This script derives it from
FairwindsOps **pluto**'s machine-readable ``versions.json`` (which tracks the
Kubernetes Deprecated API Migration Guide) and writes it into our schema.

Run manually or in CI (a scheduled job opens a PR when upstream changes):

    python mcp/scripts/gen_api_deprecations.py            # fetch + write
    python mcp/scripts/gen_api_deprecations.py --dry-run  # print, don't write

The parser (:func:`parse_pluto`) is pure and unit-tested on a small sample, so
the mapping logic is covered without a network call.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

PLUTO_VERSIONS_URL = (
    "https://raw.githubusercontent.com/FairwindsOps/pluto/master/versions.json"
)
_OUT = Path(__file__).resolve().parents[1] / "data" / "upgrades" / "api_deprecations.yaml"


def _to_minor(v: str) -> str:
    """"v1.22.0" -> "1.22"; "1.22" -> "1.22". Empty/garbage -> ""."""
    v = (v or "").strip().lstrip("vV")
    parts = v.split(".")
    if len(parts) >= 2 and parts[0].isdigit() and parts[1].isdigit():
        return f"{int(parts[0])}.{int(parts[1])}"
    return ""


def _split_api_version(api_version: str) -> tuple[str, str]:
    """"networking.k8s.io/v1beta1" -> ("networking.k8s.io", "v1beta1")."""
    if "/" in api_version:
        group, version = api_version.split("/", 1)
        return group, version
    return "", api_version


def parse_pluto(data: dict[str, Any]) -> list[dict[str, Any]]:
    """Map pluto ``versions.json`` -> our ``deprecations`` list.

    Keeps only Kubernetes core APIs (``component == "k8s"``) that have a known
    removal version — our schema is about what *breaks* on upgrade.
    """
    out: list[dict[str, Any]] = []
    for entry in data.get("deprecated-versions") or []:
        if not isinstance(entry, dict):
            continue
        if entry.get("component", "k8s") != "k8s":
            continue
        removed_in = _to_minor(entry.get("removed-in", ""))
        if not removed_in:
            continue  # deprecated-but-not-removed: not a blocker, skip for v1
        group, version = _split_api_version(entry.get("version", ""))
        kind = entry.get("kind", "")
        if not kind or not version:
            continue
        out.append(
            {
                "kind": kind,
                "group": group,
                "version": version,
                "deprecated_in": _to_minor(entry.get("deprecated-in", "")),
                "removed_in": removed_in,
                "replacement": entry.get("replacement-api") or None,
            }
        )
    out.sort(key=lambda d: (d["removed_in"], d["group"], d["kind"]))
    return out


def _dump_yaml(deprecations: list[dict[str, Any]]) -> str:
    import yaml

    header = (
        "# Kubernetes API deprecations/removals — the Upgrade Pilot's GUARANTEED core.\n"
        "# GENERATED by mcp/scripts/gen_api_deprecations.py from FairwindsOps pluto.\n"
        "# Do not hand-edit; re-run the generator instead.\n"
    )
    body = yaml.safe_dump({"deprecations": deprecations}, sort_keys=False, default_flow_style=True)
    return header + body


def _fetch(url: str) -> dict[str, Any]:
    from urllib.request import urlopen

    if not url.startswith("https://"):
        # Only https — refuse file://, http://, and other schemes so a stray
        # --url can't turn this into a local-file read or an SSRF vector.
        raise ValueError(f"--url must be an https URL, got: {url!r}")
    with urlopen(url, timeout=30) as resp:  # noqa: S310 - scheme checked above
        return json.loads(resp.read().decode("utf-8"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--url", default=PLUTO_VERSIONS_URL)
    ap.add_argument("--dry-run", action="store_true", help="print, do not write")
    args = ap.parse_args(argv)

    deprecations = parse_pluto(_fetch(args.url))
    if not deprecations:
        print("no deprecations parsed — aborting", file=sys.stderr)
        return 1
    text = _dump_yaml(deprecations)
    if args.dry_run:
        print(text)
    else:
        _OUT.write_text(text)
        print(f"wrote {len(deprecations)} deprecations to {_OUT}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
