"""Render PR title/body/branch/commit from a diagnosis + field change."""
from __future__ import annotations

import re
from dataclasses import dataclass
from urllib.parse import urlparse

from gitops.locate import FieldChange


@dataclass(frozen=True)
class PRSpec:
    title: str
    body: str
    branch: str
    commit_msg: str


def _slugify(s: str, max_len: int = 40) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return slug[:max_len].strip("-")


def _is_loopback(url: str | None) -> bool:
    if not url:
        return True
    host = (urlparse(url).hostname or "").lower()
    return host in ("127.0.0.1", "localhost", "::1", "0.0.0.0")


_MAX_BODY = 65000  # under GitHub's 65536 limit


def render_pr(*, diagnosis: dict, diff: str, change: FieldChange,
              investigation_id: str, cluster: str, tool_call_count: int,
              app_base_url: str | None, session_id: str | None,
              branch_prefix: str = "kubeastra/") -> PRSpec:
    short = investigation_id[:11]
    slug = _slugify(f"{change.name}-{change.field_path[-1]}")
    branch = f"{branch_prefix}fix-{slug}-{short}"
    title = f"fix({change.name}): {diagnosis.get('title', 'proposed change')}"

    evidence = "\n".join(f"- {e}" for e in diagnosis.get("evidence", []))
    links = ""
    if not _is_loopback(app_base_url) and session_id:
        base = app_base_url.rstrip("/")
        links = (f"\n## Full investigation\n\n"
                 f"- Replay: {base}/audit?session={session_id}\n"
                 f"- Transcript: {base}/chat?session={session_id}\n")

    body = (
        f"## Diagnosis\n\n"
        f"**Root cause:** {diagnosis.get('title', '')}\n"
        f"**Severity:** {str(diagnosis.get('severity', '')).upper()}\n"
        f"**Confidence:** {diagnosis.get('confidence', '')}\n"
        f"**Cluster:** {cluster}\n\n"
        f"## Evidence\n\n{evidence}\n\n"
        f"## Proposed change\n\n"
        f"`{change.kind}/{change.name}` — set `{'.'.join(map(str, change.field_path))}`"
        f" to `{change.new_value}` ({change.reason}).\n\n"
        f"```diff\n{diff}\n```\n"
        f"{links}\n"
        f"<sub>Auto-proposed by KubeAstra · {tool_call_count} tool calls · "
        f"Investigation `{investigation_id}`</sub>\n"
    )
    if len(body) > _MAX_BODY:
        body = body[:_MAX_BODY] + "\n\n... (truncated)\n"

    commit_msg = f"{title}\n\nAuto-generated by KubeAstra.\nInvestigation: {investigation_id}"
    return PRSpec(title=title, body=body, branch=branch, commit_msg=commit_msg)
